trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - script: |
      cd client
      npm install
      npm run build
    displayName: "Build front-end"

  - script: |
      cd backend
      npm install
      nodemon index.js
    displayName: "Build back-end"
